name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45eda4b39522 # v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178fbb3ce5d2f0289889aa7bf # v4.0.0
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:preview

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@373f7f263a3333eef0d78f72be82eb51ea6a6506 # v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
